Cs 565 miw ssi agent lib sync the upstream repository
Cofinity-X/SSI-agent-lib pull request #35
Opened 2024-03-06 12:29 UTC by PManaras

2024-03-14 13:18 UTC, mustafasalfiti commented on src/main/java/org/eclipse/tractusx/ssi/lib/SsiLibrary.java
> +
should we change the name to SSILibrary?

2024-03-14 13:19 UTC, mustafasalfiti commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/ec/ECKeyGenerator.java
Copywrite should be added to this file

2024-03-14 13:20 UTC, mustafasalfiti commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/util/SignerUtil.java
> +package org.eclipse.tractusx.ssi.lib.crypt.util;
Copywrite should be added to this file

2024-03-14 21:01 UTC, mustafasalfiti requested changes
Tested with MIW and Revocation Service all Xray tests as well tests are working,
thank you for writting and refactoring some of the tests.

however you are missing the copywrite on the new files i noted some of them but all the new test files are missing that!.

2024-03-19 10:58 UTC, mustafasalfiti approved these changes

2024-03-20 06:54 UTC, nitin-vavdiya approved these changes

2024-03-21 16:46 UTC, merged